config/routes.rb
Curex::Application.routes.draw do
  get 'listings/get_index' => 'listings#get_index'
  delete 'listings/:id/:password' => 'listings#destroy', :constraints => { :password => /.*/ }
  get 'listings/:id/edit/:password' => 'listings#edit', :constraints => { :password => /.*/ }
  get 'listings/:id/:password' => 'listings#show', :constraints => { :password => /.*/ }
  resources :listings
  root :to => "listings#index"
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user

  #TODO: implement the same functionality without method_missing
  def method_missing(*attributes)
    if (attributes[0][/_safe$/])
      html_safe_string = send(attributes[0].to_s.gsub(/_safe$/,"").intern).html_safe
      CGI::unescapeElement( CGI::escapeHTML(html_safe_string), "BR" )
    else
      super
    end
  end

  def password_or_master_password?(str)
    (str == user.password) || (str == Curex::Application.config.master_password)
  end

  def contact
    user.name + "<br />" + user.contact
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings
  after_initialize :generate_password

  validates_presence_of :contact
  validates_format_of :password, :with => /^[a-zA-Z0-9\._]+$/

  #TODO: implement the same functionality without method_missing
  def method_missing(*attributes)
    if (attributes[0][/_safe$/])
      html_safe_string = send(attributes[0].to_s.gsub(/_safe$/,"").intern).html_safe
      CGI::unescapeElement( CGI::escapeHTML(html_safe_string), "BR" )
    else
      super
    end
  end

  private
  def generate_password

    if (password.nil?) || (password.empty?)
      self.password = (Array.new(5) {ActiveSupport::SecureRandom.random_number(10)}).join("")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  helper 'listings'

  def index
    @yui = true
  end

  def get_index
    returnValue = Hash.new
    records = Array.new
    @listings = Listing.all(:order => 'updated_at desc')

    @listings.each do |listing|
      tempHash = {}
      id = listing.id
      tempHash["source_amount"] = listing.source_amount_safe
      tempHash["source_type"] = t("listings.types")[listing.source_type.to_i]
      tempHash["rate"] = listing.rate_safe
      tempHash["target_amount"] = listing.target_amount_safe
      tempHash["target_type"] = t("listings.types")[listing.target_type.to_i]

      #time difference in seconds
      tempHash["urgency"] = Time.now() - listing.updated_at.to_datetime
      tempHash["contact"] = listing.contact_safe
      tempHash["remarks"] = listing.remarks_safe

      tempHash["link"] =  (listing.removed) ? "" : "<a href=\"" +  listing_url(listing) + "\">#{ t 'listings.index.edit' }</a>"
      tempHash["removed"] = listing.removed
      records.push(tempHash)
    end
    returnValue["records"] = records
    returnValue["pageSize"] = 20
    returnValue["recordsReturned"] = @listings.size
    returnValue["totalRecords"] = @listings.size
    returnValue["startIndex"] = 0
    returnValue["sort"] = "urgency"
    returnValue["dir"] = "desc"
    respond_to do |format|
      format.json  { render :json => returnValue.to_json }
    end
  end

  def new
    @listing = Listing.new
    @listing.source_type = 2
    @listing.target_type = 1

    if cookies[:listing_user]
      @user = @listing.build_user(Marshal.load(cookies[:listing_user]))
    else
      @user = @listing.build_user()
    end
  end

  def create
    #cookies
    cookies[:listing_user] = {
      :value => Marshal.dump(params[:listing][:user]),
      :expires => 1.month.from_now
    }

    #I hate accepts_nested_attributes_for!!!!
    @user = User.new(params[:listing][:user])
    params[:listing].delete(:user)
    @listing = Listing.new(params[:listing])
    @listing.user = @user
    if (@user.save)
      #listing itself

      if @listing.save
          #strange style of login
          if (cookies[:my_links])
            links = (Marshal.load(cookies[:my_links]))
          else
            links = Array.new
          end
          links.push(@listing.id) unless (links.include?(@listing.id))
          cookies[:my_links] = {
            :value => Marshal.dump(links),
            :expires => 1.month.from_now
          }
          redirect_to((listing_url(@listing) + "/" + @user.password),\
            :alert=> (t('listings.new.password_alert') + @listing.user.password).html_safe  )
      else
          render :action => "new"
      end
    else
      render :action => "new"
    end
  end

  def show
    if (Listing.exists?(params[:id]))
      @listing = Listing.find_by_id(params[:id])
      redirect_to(listings_url) if (@listing.removed)
      redirect_to(listings_url) if (params[:password]) && (!@listing.password_or_master_password?(params[:password]))

      @current_user_admin = false
      if (cookies[:my_links])
        links = (Marshal.load(cookies[:my_links]))
        @current_user_admin= true if (links.include?(@listing.id))
      end
      #if user is admin
      @current_user_admin = true if (params[:password]) && (@listing.password_or_master_password?(params[:password]))
      params[:password] = @listing.user.password if (@current_user_admin)
    else
      redirect_to(listings_url)
    end
  end

  def edit
      if (Listing.exists?(params[:id]))
        @listing = Listing.find(params[:id])
        redirect_to(listings_url) if (@listing.removed)
        if (params[:password]) && (@listing.password_or_master_password?(params[:password]))
          @user = @listing.user
        else
          redirect_to(listings_url)
        end
      else
        redirect_to(listings_url)
      end
  end

  def update
    if (Listing.exists?(params[:id]))
        @listing = Listing.find(params[:id])
        redirect_to(listings_url) if (@listing.removed)
        if (params[:password]) && (@listing.password_or_master_password?(params[:password]))
          #cookies
          cookies[:listing_user] = {
            :value => Marshal.dump(params[:listing][:user]),
            :expires => 1.month.from_now
          }
          #I hate accepts_nested_attributes_for!!!!
          @user = @listing.user
          if ( @user.update_attributes(params[:listing][:user]) )
            params[:listing].delete(:user)

            if @listing.update_attributes(params[:listing])
              redirect_to((listing_url(@listing) + "/" + @user.password),\
                :alert=> (t('listings.new.password_alert') + @listing.user.password).html_safe )
            else
              render :action => "edit"
            end
          else
              render :action => "edit"
          end
        end
    else
      redirect_to(listings_url)
    end
  end

  def destroy
    if (Listing.exists?(params[:id]))
      @listing = Listing.find(params[:id])
      redirect_to(listings_url) if (@listing.removed)
      if (params[:password]) && (@listing.password_or_master_password?(params[:password]))
        @listing.update_attribute(:removed, true)
      end
    end
    redirect_to(listings_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Curex</title>

  <% if (@yui) %>
    <%= stylesheet_link_tag 'datatable', 'application', 'button', 'fonts-min'%>
    <%= javascript_include_tag 'prototype', 'rails', 'application','yahoo-dom-event',\
        'connection-min', 'element-min', 'paginator-min', 'json-min', 'datasource-min', 'datatable-min', 'button-min' %>
  <% else %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'prototype','rails', 'application'%>
  <% end %>

  <%#= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body <%= render :inline =>"class=\"yui-skin-sam\"" if @yui%>>

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= javascript_tag do %>
    <!--function calculateTargetAmount(){-->
        <!--var mult1 = parseFloat($('listing_source_amount').value);-->
        <!--var mult2 = parseFloat($('listing_rate').value);-->

        <!--if ( !isNaN(mult1) && !isNaN(mult2) ){-->
            <!--$('listing_target_amount').value = new String(mult1 * mult2);-->
        <!--}-->
        <!--return null;-->
    <!--}-->
    <!--document.observe("dom:loaded", function() {-->

      <!--$('listing_source_amount').observe('keyup', function(event) {-->
        <!--calculateTargetAmount();-->
      <!--});-->
      <!--$('listing_rate').observe('keyup', function(event) {-->
        <!--calculateTargetAmount();-->
      <!--});-->
    <!--});-->

<% end %>

    <%= form_for (@listing) do |listing_form| %>
        <%= (hidden_field_tag :password, params[:password]) if (params[:password]) %>
        <% if @listing.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@listing.errors.count, "@listing") %> <%=t 'listings.new.errors'%>:</h2>

          <ul>
          <% @listing.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
        <table>
            <tr><td align="right"><%=  t 'listings.new.source_type' %></td><td><%= listing_form.select     :source_type, t('listings.types').map{|key, value| [value, key]} %></td></tr>
            <tr><td align="right"><%=  t 'listings.show.source_amount' %>: </td><td><%= listing_form.text_field :source_amount %></td></tr>
            <tr><td><br/></td><td></td></tr>
            <tr><td align="right"><%=  t 'listings.new.rate' %></td><td><%= listing_form.text_field :rate %></td></tr>
            <tr><td><br/></td><td></td></tr>
            <tr><td align="right"><%=  t 'listings.new.target_type' %></td><td><%= listing_form.select     :target_type, t('listings.types').map{|key, value| [value, key]} %></td></tr>
            <tr><td align="right"><%=  t 'listings.new.target_amount' %>: </td><td><%= listing_form.text_field :target_amount %></td></tr>
            <tr><td><br/></td><td></td></tr>
            <tr><td align="right"><%=  t 'listings.new.remarks' %>: </td><td><%= listing_form.text_area  :remarks, :cols=>40, :rows=>5  %></td></tr>
            <tr><td colspan="2"><hr></td></tr>
            <%= listing_form.fields_for @listing.user do |user_fields| %>
                <tr><td align="right" width="250"><%=  t 'listings.new.password' %>
                                <br /><u><%= t 'listings.new.password_format' %></u></td><td><%= user_fields.text_field :password %></td></tr>
                <tr><td align="right"><%=  t 'listings.new.name' %></td><td><%= user_fields.text_field :name  %></td></tr>
                <tr><td align="right"><u><%=  t 'listings.new.contact' %></u></td><td><%= user_fields.text_area  :contact, :cols=>40, :rows=>2 %></td></tr>
            <% end %>
            <tr><td><%= t 'listings.new.required' %></td><td><%= listing_form.submit t("form.#{params[:action]}.submit")%></td></tr>

        </table>
    <% end %>

app/views/listings/edit.html.erb
<h1><%= t 'listings.edit.edit_listing' %></h1>

<%= render 'form' %>

<%= link_to t('listings.edit.listings'), listings_path %>

app/views/listings/index.html.erb
<h1><%= t 'listings.index.listings' %></h1>
<p><%= link_to( t('listings.index.new_listing'), new_listing_url) %></p>

<style type="text/css">
#doc {
	width: 700px;
	margin: 0 auto;
}
#hd {
	text-align: center;
}
.yui-skin-sam .yui-dt .yui-dt-col-state1,
.yui-skin-sam .yui-dt .yui-dt-col-state2,
.yui-skin-sam .yui-dt .yui-dt-col-state3 {
	width: 133px;
	text-align: right;
}
#containerContainer {
	width: 100%;
	height: 64px;
	padding: 8px 0;
}
#genderRadioContainer {
	float: left;
	width: 301px;
}
</style>
<!--
<div id="containerContainer">
    <div id="currRadioContainer">
    <p><%= t 'listings.index.select_curr' %></p>
        <input type="radio" name="currButton" value="<%= t 'listings.index.all' %>" checked>
        <% t('listings.types').each do |key,value| %>
            <input id="<%= key %>" type="radio" name="currButton" value="<%= value %>">
        <% end %>
    </div>
</div>
-->
<p>
    <br />
</p>

<!--BEGIN SOURCE CODE FOR data table =============================== -->

<div id="dynamicdata"></div>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.curex.DynamicData = function() {
//        // localside filtering data
//        YAHOO.util.Event.on('currButton','click',function (e) {
//            //setTimeout(Ex.updateFilter,600);
//            alert("changed");
//        });
//        // Create the Radio Buttons for selecting a gender filter.
//        var currButtons = new YAHOO.widget.ButtonGroup('currRadioContainer');
        //div implementation
        function integerDivision(x, y, z){
            var d = Math.round(x/y - x%y/y);
            if (d>z) d %= z;
            var returnValue = "";
            if (d>0){
                returnValue = d.toString();
            }
            else{
                returnValue = "00";
            }
            return returnValue;
        }
        //custom formatters
        // Define a custom row formatter function
        var rowFormatter = function(elTr, oRecord) {
            if (oRecord.getData('removed') == true) {
                Dom.addClass(elTr, 'mark');

            }
            return true;
        };

        var markFormatter = function(elLiner, oRecord, oColumn, oData) {
                elLiner.innerHTML = "<b>" + oData + "</b>";
            };
        YAHOO.widget.DataTable.Formatter.markFormatter = markFormatter;

        var listing_urlFormatter = function(elLiner, oRecord, oColumn, oData) {
                   var link = oData;
                   elLiner.innerHTML = link;
               };
        YAHOO.widget.DataTable.Formatter.listing_urlFormatter = listing_urlFormatter;

        var customDateFormatter = function(elLiner, oRecord, oColumn, oData) {

                       var dateDifference =oData;
                       var renderedValue = "";
                       //days
                       var days = integerDivision(dateDifference, (60*60*24), 1000);
                       if ( days == 1){

                           renderedValue += (days+ " <%= t 'listings.index.one_day' %>");
                       }
                       else if ( ( days >= 2) && (days <=4) ){

                           renderedValue += (days + " <%= t 'listings.index.2_4_days' %>");
                       }
                       else if (days > 4){

                           renderedValue += (days + " <%= t 'listings.index.many_days' %>");
                       }

                       renderedValue += (" ");

                       // hours
                       var hours = integerDivision(dateDifference, (60*60), 24);
                       var tempHours = "";
                       while ( (tempHours.length +hours.toString().length)< 2)
                         tempHours += ("0");
                       renderedValue += (tempHours + hours.toString());

                       //minutes
                       var minutes = integerDivision(dateDifference, (60), 60);
                       renderedValue += (":");
                       var tempMinutes = "";
                       while ( (tempMinutes.length + minutes.toString().length)< 2)
                         tempMinutes += ("0");
                       renderedValue += (tempMinutes + minutes.toString());

                       elLiner.innerHTML = renderedValue;
                   };
        YAHOO.widget.DataTable.Formatter.customDateFormatter = customDateFormatter;

        // Column definitions
        var myColumnDefs = [ // sortable:true enables sorting
            {key:"source_type", label:"<%=t 'listings.index.source_type' %>", sortable:true},
            {key:"source_amount", label:"<%=t 'listings.index.source_amount' %>", sortable:true},
            {key:"rate", label:"<%=t 'listings.index.rate' %>", sortable:true, formatter: "markFormatter"},
            {key:"target_type", label:"<%=t 'listings.index.target_type' %>", sortable:true},
            {key:"target_amount", label:"<%=t 'listings.index.target_amount' %>", sortable:true},
            {key:"urgency", label:"<%=t 'listings.index.urgency' %>", sortable:true, formatter:"customDateFormatter"},
            {key:"contact", label:"<%=t 'listings.index.contact' %>", sortable:false},
            {key:"remarks", label:"<%=t 'listings.index.remarks' %>", sortable:false},
            {key:"link", label:"<%=t 'listings.index.link' %>", sortable:false, formatter:"listing_urlFormatter"}
        ];

        // DataSource instance
        var myDataSource = new YAHOO.util.DataSource("/listings/get_index/");
        myDataSource.responseType = YAHOO.util.DataSource.TYPE_JSON;
        myDataSource.responseSchema = {
            resultsList: "records",
            fields: [
            {key:"source_type"},
            {key:"source_amount"},
            {key:"rate"},
            {key:"target_type"},
            {key:"target_amount"},
            {key: "urgency"},
            {key:"contact"},
            {key:"remarks"},
            {key: "link"},
            {key: "removed"}
            ],
            metaFields: {
                totalRecords: "totalRecords" // Access to value in the server response
            }
        };

        // DataTable configuration
        var myConfigs = {
            initialRequest: "", // Initial request for first page of data for example sort=id&dir=asc&startIndex=0&results=25
            dynamicData: false, // Enables dynamic server-driven data
            sortedBy : {key:"urgency", dir:YAHOO.widget.DataTable.CLASS_ASC}, // Sets UI initial sort arrow
            paginator: new YAHOO.widget.Paginator({ rowsPerPage:15 }), // Enables pagination
            formatRow: rowFormatter
//            formatColumn: markFormatter

        };

        // DataTable instance
        var myDataTable = new YAHOO.widget.DataTable("dynamicdata", myColumnDefs, myDataSource, myConfigs);
        // Update totalRecords on the fly with value from server
        myDataTable.handleDataReturnPayload = function(oRequest, oResponse, oPayload) {
            oPayload.totalRecords = oResponse.meta.totalRecords;
            return oPayload;
        }

        return {
            ds: myDataSource,
            dt: myDataTable
        };

    }();
});
</script>

<!--END SOURCE CODE FOR data table =============================== -->

<br />

app/views/listings/new.html.erb
<h1><%= t 'listings.new.new_listing'%></h1>
<p>
    <%= render 'form' %>
</p>
<br />
<%= link_to t('listings.edit.listings'), listings_path %>

app/views/listings/show.html.erb
<% unless @current_user_admin  %>
    <%= javascript_tag do %>
        document.observe("dom:loaded", function() {
            var password=window.prompt('<%= t "listings.show.password_prompt" %>',"");
            if ( (password==null) || (password=="") ) {

                window.location = '<%=listings_path%>';
            }
            else {
                window.location = document.URL + "/" + password;
            }
        });
    <% end %>
<% end %>

<h1><%= t 'listings.show.listing'%>(<%= t 'listings.show.created' %>: <%= l @listing.created_at, :format=>:date_time24  %>)</h1>

<% if (params[:password]) && ( @listing.password_or_master_password?(params[:password]) )%>
    <%= link_to t('listings.show.edit'), (edit_listing_path(@listing) + "/" + params[:password]) %>
    <%= link_to(t('listings.show.destroy'), (listing_url(@listing) + "/" + params[:password]), :confirm => t('listings.show.destroy_confirm'), :method => :delete) %>
<%end%>
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<p>
    <table>
            <tr><td align="right"><%=  t 'listings.show.source_type' %></td><td><%= t("listings.types")[@listing.source_type.to_i] %></td></tr>
            <tr><td align="right"><%=  t 'listings.show.source_amount' %></td><td><%= @listing.source_amount %></td></tr>
            <tr><td><br/></td><td></td></tr>
            <tr><td align="right"><%=  t 'listings.show.rate' %></td><td><%= @listing.rate %></td></tr>
            <tr><td><br/></td><td></td></tr>
            <tr><td align="right"><%=  t 'listings.show.target_type' %></td><td><%= t("listings.types")[@listing.target_type.to_i] %></td></tr>
            <tr><td align="right"><%=  t 'listings.show.target_amount' %></td><td><%= @listing.target_amount %></td></tr>
            <tr><td><br/></td><td></td></tr>
            <tr><td align="right"><%=  t 'listings.show.remarks' %></td><td><%= @listing.remarks %></td></tr>
            <tr><td colspan="2"><hr></td></tr>

            <tr><td align="right"><%=  t 'listings.show.name' %></td><td><%= @listing.user.name  %></td></tr>
            <tr><td align="right"><%=  t 'listings.show.contact' %></td><td><%= @listing.user.contact   %></td></tr>
    </table>
</p>
<br />
<%= link_to t('listings.edit.listings'), listings_path %>